"""empty message

Revision ID: 0f2211e36ee6
Revises: 
Create Date: 2017-05-13 19:28:25.204000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f2211e36ee6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('status', sa.Integer(), nullable=True))
    op.add_column('trips', sa.Column('visibility', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'visibility')
    op.drop_column('trips', 'status')
    # ### end Alembic commands ###
